import { Card } from './types';

// ============================================================
// Card Catalogue — Pioneer through Climax species
// Moisture scale: 0=bone dry, 1=arid, 2=dry, 3=moderate, 4=moist, 5=submerged
// Light scale: 1=shade, 2=partial, 3=full sun
// Nutrients scale: 1=poor, 2=low, 3=moderate, 4=rich, 5=mineral-rich
// ============================================================

export const ALL_CARDS: Card[] = [
  // ---- PIONEER PRODUCERS ----
  {
    id: 'crust-lichen',
    name: 'Crust Lichen',
    type: 'species',
    description: 'Hardy pioneer organism. Retains moisture on bare rock. Tolerates dry to moderate conditions.',
    cost: { biomass: 1, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 1, nutrients: 0, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'pioneer',
    tags: ['pioneer'],
    placement: { minMoisture: 0, maxMoisture: 3, minLight: 2, maxLight: 3 },
    adjacencyEffect: { moisture: 1 },
    propagates: true,
    maxPropagation: 1,
    sprite: 'lichen',
    flavorText: 'The first foothold of life on bare stone.',
  },
  {
    id: 'spore-moss',
    name: 'Spore Moss',
    type: 'species',
    description: 'Low-growing moss. Builds thin soil layer. +1 nutrients to adjacent hexes. Needs some moisture.',
    cost: { biomass: 1, nutrients: 0, water: 1 },
    incomePerTurn: { biomass: 1, nutrients: 0, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'pioneer',
    tags: ['pioneer'],
    placement: { minMoisture: 2, maxMoisture: 4, minLight: 1, maxLight: 3 },
    adjacencyEffect: { nutrients: 1 },
    propagates: true,
    maxPropagation: 2,
    sprite: 'moss',
    flavorText: 'Tiny spores colonize every damp crevice.',
  },
  {
    id: 'pioneer-fern',
    name: 'Pioneer Fern',
    type: 'species',
    description: 'Early vascular plant. Chains: draws Soil Crust event card. Moderate moisture and light.',
    cost: { biomass: 2, nutrients: 1, water: 1 },
    incomePerTurn: { biomass: 2, nutrients: 0, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'pioneer',
    tags: ['pioneer'],
    placement: { minMoisture: 2, maxMoisture: 4, minLight: 2, maxLight: 3, minNutrients: 1 },
    chainDraw: 'soil-crust-event',
    sprite: 'fern',
    flavorText: 'Unfurling fronds reach for the light.',
  },
  {
    id: 'blue-green-algae',
    name: 'Blue-Green Algae',
    type: 'species',
    description: 'Aquatic pioneer. Only lives in water. Propagates to adjacent water hexes. N-fixer.',
    cost: { biomass: 1, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 1, nutrients: 1, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'pioneer',
    tags: ['pioneer', 'aquatic', 'n-fixer'],
    placement: { hexType: ['water'], minMoisture: 5, maxMoisture: 5 },
    propagates: true,
    maxPropagation: 3,
    sprite: 'algae',
    flavorText: 'Ancient photosynthesizers painting the water green.',
  },
  // ---- PIONEER DECOMPOSERS ----
  {
    id: 'mycorrhizal-fungi',
    name: 'Arbuscular Mycorrhizae',
    type: 'species',
    description: 'Fungal network. Adjacent plant cards gain +1 biomass/turn. Needs some moisture and nutrients.',
    cost: { biomass: 2, nutrients: 1, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 1, water: 0 },
    trophicLevel: 'decomposer',
    successionStage: 'pioneer',
    tags: ['fungal', 'decomposer'],
    placement: { minMoisture: 1, maxMoisture: 4, minNutrients: 1, maxNutrients: 5, minLight: 1, maxLight: 3 },
    adjacencyEffect: { biomassPerTurn: 1 },
    sprite: 'fungi',
    flavorText: 'The wood-wide web connects all.',
  },
  // ---- N-FIXER ----
  {
    id: 'n-fixing-shrub',
    name: 'N-Fixing Shrub',
    type: 'species',
    description: 'Nitrogen fixer. +2 nutrients/turn. Needs moderate moisture and full/partial light.',
    cost: { biomass: 3, nutrients: 0, water: 2 },
    incomePerTurn: { biomass: 1, nutrients: 2, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'pioneer',
    tags: ['n-fixer', 'pioneer'],
    placement: { minMoisture: 2, maxMoisture: 4, minLight: 2, maxLight: 3, minNutrients: 1 },
    adjacencyEffect: { nutrients: 1 },
    sprite: 'shrub',
    flavorText: 'Bacterial partners enrich the soil.',
  },
  // ---- GRASSLAND PRODUCERS ----
  {
    id: 'tussock-grass',
    name: 'Tussock Grass',
    type: 'species',
    description: 'Robust grass. Stabilizes soil, +1 moisture to adjacent. Moderate moisture/nutrients, good light.',
    cost: { biomass: 2, nutrients: 2, water: 1 },
    incomePerTurn: { biomass: 2, nutrients: 0, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'grassland',
    tags: ['pioneer'],
    placement: { minMoisture: 2, maxMoisture: 4, minLight: 2, maxLight: 3, minNutrients: 2 },
    adjacencyEffect: { moisture: 1 },
    propagates: true,
    maxPropagation: 2,
    sprite: 'grass',
    flavorText: 'Dense tussocks carpet the plains.',
  },
  {
    id: 'wildflower-meadow',
    name: 'Wildflower Meadow',
    type: 'species',
    description: 'Angiosperm. Synergizes with pollinators. Needs moist, nutrient-rich soil with good light.',
    cost: { biomass: 3, nutrients: 2, water: 2 },
    incomePerTurn: { biomass: 3, nutrients: 0, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'grassland',
    tags: ['angiosperm'],
    placement: { minMoisture: 3, maxMoisture: 4, minLight: 2, maxLight: 3, minNutrients: 2 },
    sprite: 'flower',
    flavorText: 'A riot of color attracts pollinators from afar.',
  },
  // ---- GRASSLAND CONSUMERS ----
  {
    id: 'pollinator-bee',
    name: 'Pollinator Bee',
    type: 'species',
    description: 'Must be adjacent to angiosperm. +1 biomass/turn to neighbors. Needs warmth and light.',
    cost: { biomass: 3, nutrients: 0, water: 1 },
    incomePerTurn: { biomass: 1, nutrients: 0, water: 0 },
    trophicLevel: 'consumer',
    successionStage: 'grassland',
    tags: ['pollinator'],
    placement: { minMoisture: 1, maxMoisture: 4, minLight: 2, maxLight: 3, adjacentTag: 'angiosperm' },
    adjacencyEffect: { biomassPerTurn: 1 },
    sprite: 'bee',
    flavorText: 'Essential connectors of the flowering world.',
  },
  {
    id: 'grazer',
    name: 'Prairie Grazer',
    type: 'species',
    description: 'Herbivore. Propagates slowly. Needs open grassland conditions.',
    cost: { biomass: 4, nutrients: 1, water: 2 },
    incomePerTurn: { biomass: 2, nutrients: 0, water: 0 },
    trophicLevel: 'consumer',
    successionStage: 'grassland',
    tags: ['herbivore', 'prey'],
    placement: { minMoisture: 2, maxMoisture: 4, minLight: 2, maxLight: 3, minNutrients: 2 },
    propagates: true,
    maxPropagation: 1,
    sprite: 'grazer',
    flavorText: 'Great herds shape the landscape.',
  },
  {
    id: 'decomposer-guild',
    name: 'Decomposer Guild',
    type: 'species',
    description: 'Adjacent species generate +1 nutrients/turn. Thrives in moist, shady conditions.',
    cost: { biomass: 2, nutrients: 0, water: 1 },
    incomePerTurn: { biomass: 0, nutrients: 2, water: 0 },
    trophicLevel: 'decomposer',
    successionStage: 'grassland',
    tags: ['decomposer', 'fungal'],
    placement: { minMoisture: 2, maxMoisture: 4, minNutrients: 1, minLight: 1, maxLight: 3 },
    adjacencyEffect: { nutrientsPerTurn: 1 },
    sprite: 'decomposer',
    flavorText: 'Recycling nutrients back into the web of life.',
  },
  // ---- WOODLAND ----
  {
    id: 'canopy-oak',
    name: 'Canopy Oak',
    type: 'species',
    description: 'Tall canopy tree. Adjacent hexes -1 light. Chains: draw shade-tolerant understory. Needs rich soil.',
    cost: { biomass: 5, nutrients: 3, water: 3 },
    incomePerTurn: { biomass: 4, nutrients: 0, water: 1 },
    trophicLevel: 'producer',
    successionStage: 'woodland',
    tags: ['canopy'],
    placement: { minMoisture: 3, maxMoisture: 4, minLight: 3, maxLight: 3, minNutrients: 3 },
    adjacencyEffect: { light: -1 },
    chainDraw: 'shade-fern',
    sprite: 'oak',
    flavorText: 'A cathedral of branches shelters the understory.',
  },
  {
    id: 'shade-fern',
    name: 'Shade Fern',
    type: 'species',
    description: 'Thrives under canopy. Low cost, steady income. Needs shade and moisture.',
    cost: { biomass: 1, nutrients: 1, water: 1 },
    incomePerTurn: { biomass: 2, nutrients: 0, water: 0 },
    trophicLevel: 'producer',
    successionStage: 'woodland',
    tags: ['shade-tolerant'],
    placement: { minMoisture: 2, maxMoisture: 4, maxLight: 2, minLight: 1, minNutrients: 2 },
    sprite: 'shade-fern',
    flavorText: 'Delicate fronds unfurl in dappled light.',
  },
  {
    id: 'woodland-predator',
    name: 'Forest Predator',
    type: 'species',
    description: 'Apex predator. Adjacent prey +2 biomass/turn (trophic cascade). Must be near prey.',
    cost: { biomass: 6, nutrients: 2, water: 2 },
    incomePerTurn: { biomass: 3, nutrients: 0, water: 0 },
    trophicLevel: 'consumer',
    successionStage: 'woodland',
    tags: ['predator'],
    placement: { minMoisture: 1, maxMoisture: 4, minLight: 1, maxLight: 3, adjacentTag: 'prey' },
    adjacencyEffect: { biomassPerTurn: 2 },
    sprite: 'predator',
    flavorText: 'The forest holds its breath.',
  },
  // ---- CLIMAX ----
  {
    id: 'old-growth-tree',
    name: 'Old-Growth Giant',
    type: 'species',
    description: 'Climax canopy species. Massive biomass income. Needs rich, moist soil and full sun.',
    cost: { biomass: 8, nutrients: 4, water: 4 },
    incomePerTurn: { biomass: 6, nutrients: 1, water: 1 },
    trophicLevel: 'producer',
    successionStage: 'climax',
    tags: ['canopy'],
    placement: { minMoisture: 3, maxMoisture: 4, minLight: 3, maxLight: 3, minNutrients: 4 },
    adjacencyEffect: { light: -1, moisture: 1 },
    sprite: 'giant-tree',
    flavorText: 'Centuries of growth in a single trunk.',
  },
  {
    id: 'apex-raptor',
    name: 'Apex Raptor',
    type: 'species',
    description: 'Top predator. +3 biomass/turn to adjacent prey. Must be near prey.',
    cost: { biomass: 8, nutrients: 2, water: 2 },
    incomePerTurn: { biomass: 4, nutrients: 0, water: 0 },
    trophicLevel: 'consumer',
    successionStage: 'climax',
    tags: ['predator'],
    placement: { minMoisture: 1, maxMoisture: 4, minLight: 2, maxLight: 3, adjacentTag: 'prey' },
    adjacencyEffect: { biomassPerTurn: 3 },
    sprite: 'raptor',
    flavorText: 'Soaring above the canopy, master of all it surveys.',
  },
  // ---- ABIOTIC MODIFIERS ----
  {
    id: 'drainage-redirect',
    name: 'Drainage Redirect',
    type: 'abiotic',
    description: 'Target hex +2 moisture, adjacent hexes +1 moisture. Permanent. Any normal hex.',
    cost: { biomass: 4, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: { hexType: ['normal'] },
    sprite: 'water-channel',
    flavorText: 'Redirecting the flow of water across the landscape.',
  },
  {
    id: 'mineral-amendment',
    name: 'Mineral Amendment',
    type: 'abiotic',
    description: 'Target hex +3 nutrients. Permanent. Any normal hex.',
    cost: { biomass: 3, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: { hexType: ['normal'] },
    sprite: 'minerals',
    flavorText: 'Enriching the soil with essential minerals.',
  },
  {
    id: 'slope-grading',
    name: 'Slope Grading',
    type: 'abiotic',
    description: 'Converts rock hex to normal. Enables species placement.',
    cost: { biomass: 5, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: { hexType: ['rock'] },
    sprite: 'pickaxe',
    flavorText: 'Reshaping the terrain by hand.',
  },
  // ---- EVENT CARDS ----
  {
    id: 'good-rain-year',
    name: 'Good Rain Year',
    type: 'event',
    description: 'All hexes +1 moisture this turn. Draw 1 card.',
    cost: { biomass: 0, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: {},
    sprite: 'rain',
    flavorText: 'The skies open generously.',
  },
  {
    id: 'mast-seed-event',
    name: 'Mast Seed Event',
    type: 'event',
    description: 'One species card in hand costs 0 biomass this turn.',
    cost: { biomass: 0, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: {},
    sprite: 'seed',
    flavorText: 'An extraordinary year of seed production.',
  },
  {
    id: 'warm-winter',
    name: 'Warm Winter',
    type: 'event',
    description: 'All species cards cost -1 biomass this turn (min 0).',
    cost: { biomass: 0, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: {},
    sprite: 'sun',
    flavorText: 'A mild winter lets life flourish.',
  },
  {
    id: 'soil-crust-event',
    name: 'Soil Crust Formation',
    type: 'event',
    description: 'All hexes +1 nutrients this turn.',
    cost: { biomass: 0, nutrients: 0, water: 0 },
    incomePerTurn: { biomass: 0, nutrients: 0, water: 0 },
    tags: [],
    placement: {},
    sprite: 'soil',
    flavorText: 'Biological soil crusts stabilize the ground.',
  },
];

export function getCardById(id: string): Card | undefined {
  return ALL_CARDS.find(c => c.id === id);
}

export function getStarterDeck(): Card[] {
  const starterIds = [
    'crust-lichen', 'crust-lichen', 'crust-lichen',
    'spore-moss', 'spore-moss',
    'pioneer-fern', 'pioneer-fern',
    'blue-green-algae',
    'mycorrhizal-fungi',
    'n-fixing-shrub', 'n-fixing-shrub',
    'tussock-grass', 'tussock-grass',
    'wildflower-meadow',
    'pollinator-bee',
    'decomposer-guild',
    'drainage-redirect',
    'mineral-amendment',
    'good-rain-year',
    'warm-winter',
  ];
  return starterIds.map(id => {
    const card = getCardById(id);
    if (!card) throw new Error(`Card not found: ${id}`);
    return { ...card };
  });
}
